<?php
require_once __DIR__ . '/abonnements/abonnements.php';
require_once __DIR__ . '/abonnements/abonnement_repartitions.php';
require_once __DIR__ . '/abonnements/types_abonnement.php';
require_once __DIR__ . '/administration/administrateurs.php';
require_once __DIR__ . '/administration/journal_activite.php';
require_once __DIR__ . '/administration/role.php';
require_once __DIR__ . '/administration/user.php';
require_once __DIR__ . '/authentification/authentification.php';
require_once __DIR__ . '/carrousel/carrousel_medias.php';
require_once __DIR__ . '/epasses/epass_lignes.php';
require_once __DIR__ . '/epasses/epass_personnes.php';
require_once __DIR__ . '/epasses/epasses.php';    
require_once __DIR__ . '/evenements/evenements.php';
require_once __DIR__ . '/evenements/evenement_medias.php';
require_once __DIR__ . '/parametres/taxes.php';
require_once __DIR__ . '/reversements/acteur_moyens_paiement.php';
require_once __DIR__ . '/reversements/acteurs_reversement.php';
require_once __DIR__ . '/reversements/comptes_expediteur.php';
require_once __DIR__ . '/reversements/regle_reversement_epass.php';
require_once __DIR__ . '/reversements/regle_reversement_repartitions.php';
require_once __DIR__ . '/reversements/reversement_lignes.php';
require_once __DIR__ . '/reversements/reversements.php';
require_once __DIR__ . '/sites touristiques/site_frais_supplementaires.php';
require_once __DIR__ . '/sites touristiques/site_horaires.php';
require_once __DIR__ . '/sites touristiques/site_medias.php';
require_once __DIR__ . '/sites touristiques/site_tarifs.php';
require_once __DIR__ . '/sites touristiques/sites_touristiques.php';
require_once __DIR__ . '/temoignages/temoignages.php';
require_once __DIR__ . '/utilisateurs mobile/acteurs_mobile.php';
require_once __DIR__ . '/utilisateurs mobile/avis_reponses.php';
require_once __DIR__ . '/utilisateurs mobile/avis.php';
require_once __DIR__ . '/utilisateurs mobile/catalogue_articles.php';
require_once __DIR__ . '/utilisateurs mobile/catalogue_medias.php';
require_once __DIR__ . '/utilisateurs mobile/contestations.php';
require_once __DIR__ . '/utilisateurs mobile/utilisateurs_mobile.php';
require_once __DIR__ . '/visiteurs/visiteurs.php';
require_once __DIR__ . '/visiteurs/visites.php';